import Link from "next/link";

import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";
import UserAuthForm from "@/components/ui/UserAuthForm";

export const metadata = {
  title: "Farvest sign in",
  description: "Generated by create next app",
};

const signIn = () => {
  return (
    <section>
      <div
        style={{
          backgroundImage: `url("https://res.cloudinary.com/dphkngzyu/image/upload/v1717838838/Nextjs/jvojv5vdjlct3puhagc1.jpg")`,
          height: "100vh",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
        }}
        className="container relative h-screen flex-col items-center justify-center grid lg:max-w-none lg:grid-cols-2 lg:px-0"
      >
        <div className="relative hidden h-full flex-col  p-10 text-white lg:flex dark:border-r">
          <div className="relative z-20 flex items-center font-semibold text-2xl text-black">
            <Link href="http://localhost:3000/">Farvest</Link>
          </div>
          <div className="relative z-20 mt-auto ">
            <blockquote className="space-y-2">
              <p className="text-xl">
                &ldquo;We Connect Farmers to Harvester. Join us to ensure no
                harvest goes to waste and to keep produce fresh.&rdquo;
              </p>
              {/* <footer className="text-sm">Sofia Davis</footer> */}
            </blockquote>
          </div>
        </div>
        <div className="lg:p-8">
          <div className="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
            <div className="flex flex-col space-y-2 text-center">
              <h1 className="text-2xl font-semibold tracking-tight text-white">
                Sign In to Farvest Using Google
              </h1>
            </div>
            <UserAuthForm />
            <p className="px-8 text-center text-sm text-muted-foreground">
              By clicking continue, you agree to our{" "}
              <Link
                href="/terms"
                className="underline underline-offset-4 hover:text-primary"
              >
                Terms of Service
              </Link>{" "}
              and{" "}
              <Link
                href="/privacy"
                className="underline underline-offset-4 hover:text-primary"
              >
                Privacy Policy
              </Link>
              .
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default signIn;
