import { Raleway, Marcellus } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/services/AuthProvider";
import TrackReferrer from "@/components/TrackReferrer";
// import Navbar from "@/components/shared/Navbar";
// import Footer from "@/components/shared/Footer";

const raleway = Raleway({ subsets: ["latin"] });
const marcellus = Marcellus({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-marcellus",
});

export const metadata = {
  title: "Farvest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className} ${marcellus.variable}`}>
        <main>
          <AuthProvider>
            {/* <Navbar /> */}
            <TrackReferrer />
            {children}
            {/* <Footer /> */}
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
