import { Raleway, Marcellus } from "next/font/google";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"] });
const marcellus = Marcellus({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-marcellus",
});

export const metadata = {
  title: "Farvest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className} ${marcellus.variable}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
